[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
feels = "B3w6rjs2vDjr6eKUXUiERV44BXud3nRqshctMp5p4au4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
