[features]
seeds = true

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
feels = "2FgA6YfdFNGgX8YyPKqSzhFGNvatRD5zi1yqCCFaSjq1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"


