[package]
name = "compare-idl-sdk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "compare-idl-sdk"
path = "compare_idl_sdk.rs"

[[bin]]
name = "compare-v2"
path = "compare_idl_sdk_v2.rs"

[workspace]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"